version: "2"

services:
  php-apache:
    build:
      context: .
      dockerfile: .docker/php-apache/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - eloquent
    ports:
      - "80:80"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sandbox
    networks:
      - eloquent
    ports:
      - "3306:3306"

networks:
  eloquent: